export interface Application {
  id: string;
  customer_name?: string;
  timestamp?: string;
  address?: string;
  status?: string;
  location?: string;
  email?: string;
  mobile_number?: string;
  secondary_number?: string;
  plan_id?: string | number;
  promo_id?: string | number;
  create_date?: string;
  create_time?: string;
  update_date?: string;
  update_time?: string;
  visit_date?: string;
  visit_by?: string;
  visit_with?: string;
  notes?: string;
  last_modified?: string;
  modified_by?: string;
  first_name?: string;
  middle_initial?: string;
  last_name?: string;
  mobile?: string;
  mobile_alt?: string;
  region_id?: string | number;
  city_id?: string | number;
  borough_id?: string | number;
  village_id?: string | number;
  address_line?: string;
  landmark?: string;
  nearest_landmark1?: string;
  nearest_landmark2?: string;
  gov_id_primary?: string;
  gov_id_secondary?: string;
  house_front_pic?: string;
  room_pic?: string;
  primary_consent?: boolean | string;
  primary_consent_at?: string;
  source?: string;
  ip_address?: string;
  user_agent?: string;
  portal_id?: string | number;
  group_id?: string | number;
}
