export interface Application {
  id: string;
  customer_name?: string;
  timestamp?: string;
  address?: string;
  address_line?: string;
  status?: string;
  location?: string;
  email?: string;
  mobile_number?: string;
  mobile?: string;
  secondary_number?: string;
  mobile_alt?: string;
  
  // Exact database field mappings from your application table
  Application_ID?: string;
  Timestamp?: string;
  Email_Address?: string;
  Region?: string;
  City?: string;
  Barangay?: string;
  Referred_by?: string;
  First_Name?: string;
  Middle_Initial?: string;
  Last_Name?: string;
  Mobile_Number?: string;
  Secondary_Mobile_Number?: string;
  Installation_Address?: string;
  Landmark?: string;
  Desired_Plan?: string;
  Proof_of_Billing?: string;
  Government_Valid_ID?: string;
  '2nd_Government_Valid_ID'?: string;
  House_Front_Picture?: string;
  I_agree_to_the_terms_and_conditions?: string;
  First_Nearest_landmark?: string;
  Second_Nearest_landmark?: string;
  Select_the_applicable_promo?: string;
  Attach_the_picture_of_your_document?: string;
  Attach_SOA_from_other_provider?: string;
  Status?: string;
  
  // Convenience properties (lowercase/friendly names)
  region?: string;
  city?: string;
  barangay?: string;
  referred_by?: string;
  first_name?: string;
  middle_initial?: string;
  last_name?: string;
  plan?: string;
  desired_plan?: string;
  landmark?: string;
  first_nearest_landmark?: string;
  second_nearest_landmark?: string;
  promo?: string;
  gov_id_primary?: string;
  gov_id_secondary?: string;
  house_front_pic?: string;
  proof_of_billing?: string;
  terms_agreement?: string;
  document_attachment?: string;
  soa_attachment?: string;
  
  // Legacy fields for compatibility with old app_applications schema
  plan_id?: string | number;
  promo_id?: string | number;
  create_date?: string;
  create_time?: string;
  update_date?: string;
  update_time?: string;
  visit_date?: string;
  visit_by?: string;
  visit_with?: string;
  notes?: string;
  last_modified?: string;
  modified_by?: string;
  region_id?: string | number;
  city_id?: string | number;
  borough_id?: string | number;
  village_id?: string | number;
  nearest_landmark1?: string;
  nearest_landmark2?: string;
  room_pic?: string;
  primary_consent?: boolean | string;
  primary_consent_at?: string;
  source?: string;
  ip_address?: string;
  user_agent?: string;
  portal_id?: string | number;
  group_id?: string | number;
}